project:
  type: website
  output-dir: docs
  resources:
      - cv.pdf
website:
  title: "Cristian Mesquida"
  navbar:
    left:
      - talks.qmd
      - teaching.qmd
      - blog.qmd
    right:
      - cv.qmd
      - icon: github
        href: https://github.com/cristianmesquida
      - text: "<img src='https://upload.wikimedia.org/wikipedia/commons/c/c7/Google_Scholar_logo.svg' style='height:20px;'>"
        href: https://scholar.google.com/citations?user=Ez2ftwgAAAAJ&hl=en&oi=ao
      - icon: envelope
        href: "mailto:c.mesquida.caldentey@tue.nl"
        
        
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

